### ISSUE TITLE
Gradle Issues

### ISSUE THREAD

**Issue by lasandaDewamuni** [k9pranav/CSC207-Project1#37]
When trying to run the project errors relating to Gradle pop up, prevent the program from being run.

- [ ] Debug the Gradle errors and pull the fix onto the main branch

**Comment by Adrien-Bonansea** [comment]
You have to Go into the elephant icon, go into setting, gradle setting, then change the "build and run" and the "Run tests using" to IntelliJ and not Gradle. Its a temporary fix but it works
